In [18]:

import numpy as np
np.set_printoptions(suppress=True)


In [19]:

N = 10


In [20]:

Curve_SIMSs = np.zeros( (N, 6) )
Curve_SIMSs.shape


(10, 6)

In [21]:

for i in range(N):
    Curve_SIMSs[i, 0] =  26 + i*30
    Curve_SIMSs[i, 1] =   (8 + i*np.random.normal(0, 0.5, 1)*10)**2
    Curve_SIMSs[i, 2] = 120 + i
    Curve_SIMSs[i, 3] =  57 + i*4
    Curve_SIMSs[i, 4] = 0.6 + i
    Curve_SIMSs[i, 5] = 768 + i*np.random.normal(0, 0.5, 1)*10


/var/folders/q4/zdsjyw0d297_fn6_fh5n7g9h0000gn/T/ipykernel_24374/2887082791.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Curve_SIMSs[i, 1] =   (8 + i*np.random.normal(0, 0.5, 1)*10)**2
/var/folders/q4/zdsjyw0d297_fn6_fh5n7g9h0000gn/T/ipykernel_24374/2887082791.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Curve_SIMSs[i, 5] = 768 + i*np.random.normal(0, 0.5, 1)*10


In [22]:

Curve_SIMSs[:, :]


array([[  26.        ,   64.        ,  120.        ,   57.        ,
           0.6       ,  768.        ],
       [  56.        ,  222.57980996,  121.        ,   61.        ,
           1.6       ,  771.58623474],
       [  86.        ,   49.12050103,  122.        ,   65.        ,
           2.6       ,  761.44940851],
       [ 116.        ,  311.45873921,  123.        ,   69.        ,
           3.6       ,  756.83807158],
       [ 146.        , 2257.82244865,  124.        ,   73.        ,
           4.6       ,  787.12941391],
       [ 176.        ,  551.94617374,  125.        ,   77.        ,
           5.6       ,  806.67388458],
       [ 206.        ,   15.41013456,  126.        ,   81.        ,
           6.6       ,  802.38214972],
       [ 236.        , 1584.05645028,  127.        ,   85.        ,
           7.6       ,  740.97421432],
       [ 266.        ,  444.28554179,  128.        ,   89.        ,
           8.6       ,  767.71367402],
       [ 296.        ,  246.37135216,

In [23]:

norm_matrix2 = Curve_SIMSs / np.linalg.norm(Curve_SIMSs, axis=0, keepdims=True)
norm_matrix2[:, :5]


array([[0.04502477, 0.02218398, 0.30471676, 0.23756187, 0.03241586],
       [0.09697642, 0.07715164, 0.30725607, 0.25423288, 0.0864423 ],
       [0.14892808, 0.01702638, 0.30979538, 0.27090389, 0.14046873],
       [0.20087973, 0.10795927, 0.31233468, 0.2875749 , 0.19449517],
       [0.25283138, 0.78261685, 0.31487399, 0.30424591, 0.24852161],
       [0.30478304, 0.19131813, 0.3174133 , 0.32091692, 0.30254804],
       [0.35673469, 0.00534153, 0.3199526 , 0.33758792, 0.35657448],
       [0.40868635, 0.54907297, 0.32249191, 0.35425893, 0.41060092],
       [0.460638  , 0.15400031, 0.32503122, 0.37092994, 0.46462735],
       [0.51258966, 0.08539838, 0.32757052, 0.38760095, 0.51865379]])

In [24]:

norm_Curve_SIMSs_means = np.mean(norm_matrix2, axis=0)
norm_Curve_SIMSs_means[ :]


array([0.27880721, 0.19920694, 0.31614364, 0.31258141, 0.27553482,
       0.31611281])

In [25]:

def softmax(x):
    return( np.exp(x)/np.exp(x).sum() )


In [26]:

a = softmax(norm_Curve_SIMSs_means[ :])


In [27]:

sum( a )


1.0